swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: |- 
    Contains all API endpoints and schemes in this codebase
    **Transactions module is not implemented yet**
    ## User Module
    * Login for user
    * Signup for user
    * Get user profile
    * Update user profile
    ## Transactions Module
    * Get all transactions for a user
    * Get a specific transaction for a user
    * Update category and/or notes for a specific transaction
  version: 'alpha 1.1.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{accountId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for fetching transactions for an user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          type: integer
          name: accountId
          required: true
          description: Numeric ID of the account link to the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved Successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Invalid token / Unauthorized
        '500':
          description: Internal Server Error
  /transactions/{accountId}/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for fetching a transaction
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: integer
          name: accountId
          required: true
          description: Numeric ID of the account link to the transaction
        - in: path
          type: integer
          name: transactionId
          required: true
          description: Numeric ID of the transaction
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Invalid token / Unauthorized
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for updating a transaction
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: integer
          name: accountId
          required: true
          description: Numeric ID of the account link to the transaction
        - in: path
          type: integer
          name: transactionId
          required: true
          description: Numeric ID of the transaction
        - in: body
          name: body
          description: Transaction update Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionsUpdate'
      responses:
        '200':
          description: User transaction updates and retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Invalid token / Unauthorized
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
      type:
        type: string
      date:
        type: string
        format: date
      categorie:
        type: integer
        format: int64
      note:
        type: string
  TransactionsUpdate:
    type: object
    properties:
      categorie:
        type: string
      note:
        type: string
